title: learn fpga
description: learn fpga
template:
  repo: learn-fpga-template
  name: learn-fpga
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
